import React, { useState } from 'react';
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import ConfidenceBadge from './ConfidenceBadge';
import { IndianRupee, Tag, Package, Copy, Check } from "lucide-react";

export default function ExecutiveSummary({ productData, classification, report }) {
  const [copied, setCopied] = useState(false);

  const verdictColors = {
    'Overpriced':    'text-red-400',
    'Underpriced':   'text-emerald-400',
    'Fair':          'text-primary',
    'Competitive':   'text-primary',
    'fairly_priced': 'text-primary',
    'Unavailable':   'text-muted-foreground',
  };
  const isUnavailableVerdict = report.pricing_verdict?.verdict === 'Unavailable';

  // Step H: Build formatted clipboard text
  const buildCopyText = () => {
    const verdictLine = report.pricing_verdict?.verdict
      ? (isUnavailableVerdict
          ? 'Pricing Verdict: Unavailable (price not extracted)'
          : `Pricing Verdict: ${report.pricing_verdict.verdict}`)
      : '';
    const lines = [
      `**${productData.name}** — ${productData.price}`,
      verdictLine,
      '',
      report.executive_summary || '',
      '',
      `Generated by Adler's Den Product Intelligence Tool`,
    ];
    return lines.filter((l, i) => !(l === '' && i === 1)).join('\n');
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildCopyText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      console.warn('Clipboard write failed');
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="relative overflow-hidden rounded-2xl border border-border bg-gradient-to-br from-card via-card to-primary/5 p-8"
    >
      <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl -translate-y-32 translate-x-32" />

      <div className="relative">
        <div className="flex flex-wrap items-start justify-between gap-4 mb-6">
          <div className="flex items-start gap-4">
            {productData.image && (
              <img 
                src={productData.image} 
                alt={productData.name} 
                className="w-20 h-20 rounded-xl object-cover border border-border bg-background/50 shadow-sm"
              />
            )}
            <div>
              <h1 className="font-heading text-2xl md:text-3xl font-bold text-foreground mb-2">
                {productData.name}
              </h1>
              <div className="flex flex-wrap items-center gap-3">
                <div className="flex items-center gap-1.5 text-primary font-heading text-xl font-semibold">
                  {typeof productData.price === 'string' && productData.price.startsWith('₹')
                    ? <span>{productData.price}</span>
                    : typeof productData.price === 'string' && !/\d/.test(productData.price)
                      ? <span className="text-muted-foreground text-base">{productData.price}</span>
                      : <><IndianRupee className="w-5 h-5" />{productData.price?.toLocaleString('en-IN')}</>
                  }
                </div>
                <Badge variant="outline" className="font-body text-xs text-muted-foreground border-border">
                  <Tag className="w-3 h-3 mr-1" />
                  {productData.category}
                </Badge>
                <Badge variant="outline" className="font-body text-xs text-muted-foreground border-border">
                  <Package className="w-3 h-3 mr-1" />
                  {classification?.type === 'hamper' ? 'Gift Hamper' : 'Single Product'}
                </Badge>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <ConfidenceBadge level={report.overall_confidence} />
            {/* Step H: Copy summary button */}
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="font-body text-xs gap-1.5 text-muted-foreground hover:text-foreground transition-colors"
            >
              {copied
                ? <><Check className="w-3.5 h-3.5 text-emerald-400" /> Copied!</>
                : <><Copy className="w-3.5 h-3.5" /> Copy</>
              }
            </Button>
          </div>
        </div>

        <div className="bg-background/50 rounded-xl p-5 border border-border/50">
          <p className="font-body text-base text-foreground/90 leading-relaxed">
            {report.executive_summary}
          </p>
        </div>

        {report.pricing_verdict && (
          <div className="mt-4 flex items-center gap-3">
            <span className="text-sm font-body text-muted-foreground">Pricing verdict:</span>
            <span className={`font-heading font-semibold text-lg ${verdictColors[report.pricing_verdict.verdict] || 'text-foreground'}`}>
              {isUnavailableVerdict ? 'Unavailable — price not extracted' : report.pricing_verdict.verdict}
            </span>
          </div>
        )}
      </div>
    </motion.div>
  );
}